package com.example.intuitivecats.factory

import com.example.intuitivecats.breeds.model.BreedItem
import com.example.intuitivecats.breeds.model.Image
import com.example.intuitivecats.breeds.model.Weight

object BreedFactory {

    fun create(
        adaptability: Int = 1,
        affection_level: Int = 2,
        alt_names: String? = "",
        bidability: Int = 3,
        cat_friendly: Int = 4,
        cfa_url: String = "",
        child_friendly: Int = 5,
        country_code: String? = "",
        country_codes: String? = "",
        description: String? = "",
        dog_friendly: Int = 6,
        energy_level: Int = 7,
        experimental: Int = 8,
        grooming: Int = 9,
        hairless: Int = 10,
        health_issues: Int = 11,
        hypoallergenic: Int = 12,
        id: String? = "",
        image: Image? = Image(1, "", "", 1),
        indoor: Int = 13,
        intelligence: Int = 14,
        lap: Int = 15,
        life_span: String? = "",
        name: String? = "",
        natural: Int = 16,
        origin: String? = "",
        rare: Int = 17,
        reference_image_id: String? = "",
        rex: Int = 18,
        shedding_level: Int = 19,
        short_legs: Int = 20,
        social_needs: Int = 21,
        stranger_friendly: Int = 22,
        suppressed_tail: Int = 23,
        temperament: String? = "",
        vcahospitals_url: String? = "",
        vetstreet_url: String? = "",
        vocalisation: Int = 24,
        weight: Weight? = Weight("", ""),
        wikipedia_url: String? = ""
    ): BreedItem = BreedItem(
        adaptability = adaptability,
        affection_level = affection_level,
        alt_names = alt_names,
        bidability = bidability,
        cat_friendly = cat_friendly,
        cfa_url = cfa_url,
        child_friendly = child_friendly,
        country_code = country_code,
        country_codes = country_codes,
        description = description,
        dog_friendly = dog_friendly,
        energy_level = energy_level,
        experimental = experimental,
        grooming = grooming,
        hairless = hairless,
        health_issues = health_issues,
        hypoallergenic = hypoallergenic,
        id = id,
        image = image,
        indoor = indoor,
        intelligence = intelligence,
        lap = lap,
        life_span = life_span,
        name = name,
        natural = natural,
        origin = origin,
        rare = rare,
        reference_image_id = reference_image_id,
        rex = rex,
        shedding_level = shedding_level,
        short_legs = short_legs,
        social_needs = social_needs,
        stranger_friendly = stranger_friendly,
        suppressed_tail = suppressed_tail,
        temperament = temperament,
        vcahospitals_url = vcahospitals_url,
        vetstreet_url = vetstreet_url,
        vocalisation = vocalisation,
        weight = weight,
        wikipedia_url = wikipedia_url
    )
}
